export const sampleData = [
  {
    PersonID: 1,
    PersonName: "joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,
    inEdit:false,
  },
  {
    PersonID: 2,
    PersonName: "2joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,
    inEdit:false,
  },
  {
    PersonID: 3,
    PersonName: "joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,inEdit:false,
  },
  {
    PersonID: 4,
    PersonName: "joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,inEdit:false,
  },
  {
    PersonID: 5,
    PersonName: "joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,inEdit:false,
  },
  {
    PersonID: 6,
    PersonName: "joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,inEdit:false,
  },
  {
    PersonID: 7,
    PersonName: "joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,inEdit:false,
  },  {
    PersonID: 8,
    PersonName: "joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,inEdit:false,
  },
  {
    PersonID: 9,
    PersonName: "joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,inEdit:false,
  },
  {
    PersonID: 10,
    PersonName: "joy",
    PersonGender: "male",
    PersonAddress: "test",
    PersonMobileNo: "034545445645",
    DateOfBirth: new Date(1996, 8, 20),
    PersonAge: 3,inEdit:false,
  },
  
];
